[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "advanced_text_processor"
version = "0.2.0"
description = "Built-in-only text processing and dataset manipulation library"
authors = [{ name = "Sinan Dede" }]
readme = "README.md"
requires-python = ">=3.9"
dependencies = []